[Sparkle0]
Meter=Image
ImageName=sparkle

[Sparkle1]
Meter=Image
ImageName=sparkle

[Sparkle2]
Meter=Image
ImageName=sparkle

[Sparkle3]
Meter=Image
ImageName=sparkle

[Sparkle4]
Meter=Image
ImageName=sparkle

[Sparkle5]
Meter=Image
ImageName=sparkle

[Sparkle6]
Meter=Image
ImageName=sparkle

[Sparkle7]
Meter=Image
ImageName=sparkle

[Sparkle8]
Meter=Image
ImageName=sparkle

[Sparkle9]
Meter=Image
ImageName=sparkle