[Meter0]
Meter=String
Text=8/9
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=0
FontFace=Segoe UI Light
FontSize=24
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter1]
Meter=String
Text=MP
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=50
FontFace=Segoe UI
FontSize=16
FontColor=54,49,56
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter2]
Meter=String
Text=8/24 - 9/8
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=92
FontFace=Segoe UI Light
FontSize=24
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter3]
Meter=String
Text=Adjust 1100 - 2000
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=142
FontFace=Segoe UI
FontSize=16
FontColor=54,49,56
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter4]
Meter=String
Text=318  BASICON S19 TH 0915 - 1045 W 0915 - 1045
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=174
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter5]
Meter=String
Text=320  BASICON S17 MW 0915 - 1045 T 1100 - 1230
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=188
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter6]
Meter=String
Text=2022 INTRODB S18 TH 1100 - 1200
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=202
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter7]
Meter=String
Text=2048 LASARE1 A51 F  0730 - 1630
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=216
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter8]
Meter=String
Text=170  SCIMATC S17 T  1245 - 1345
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=230
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter9]
Meter=String
Text=1809 SOCTEC2 S11 MW 1615 - 1745
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=244
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter10]
Meter=String
Text=www.dlsu.edu.ph/offices/registrar/schedules/enroll_ug.pdf
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=258
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

1