[Meter0]
Meter=String
Text=8/17
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=0
FontFace=Segoe UI Light
FontSize=24
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter1]
Meter=String
Text=Final Exam - CCSCAL1
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=50
FontFace=Segoe UI
FontSize=16
FontColor=54,49,56
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter2]
Meter=String
Text=G206 1030 - 1230
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=82
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter3]
Meter=String
Text=Parabola, Ellipse, Circle
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=96
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter4]
Meter=String
Text=Limits
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=110
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter5]
Meter=String
Text=Find Vert. & Hori. Asymp. via Limits
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=124
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter6]
Meter=String
Text=Continuity on Interval
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=138
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter7]
Meter=String
Text=Continuity+Differentiability of Piece Wise Func.
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=152
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter8]
Meter=String
Text=Derivatives of Alge. & Trig. Func.
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=166
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter9]
Meter=String
Text=Imp. Diff.
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=180
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter10]
Meter=String
Text=Tan. & Norm. Line
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=194
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter11]
Meter=String
Text=Word Prob. on Related Rates
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=208
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter12]
Meter=String
Text=Crit. Num., Inc. & Dec. Func, Max. & Min.
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=222
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter13]
Meter=String
Text=8/18
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=256
FontFace=Segoe UI Light
FontSize=24
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter14]
Meter=String
Text=Final Exam - DISCTRU
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=306
FontFace=Segoe UI
FontSize=16
FontColor=54,49,56
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter15]
Meter=String
Text=G203 1130 - 1430
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=338
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter16]
Meter=String
Text=8/24 - 9/8
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=372
FontFace=Segoe UI Light
FontSize=24
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter17]
Meter=String
Text=Adjust 1100 - 2000
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=422
FontFace=Segoe UI
FontSize=16
FontColor=54,49,56
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter18]
Meter=String
Text=318  BASICON S19 TH 0915 - 1045 W 0915 - 1045
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=454
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter19]
Meter=String
Text=320  BASICON S17 MW 0915 - 1045 T 1100 - 1230
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=468
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter20]
Meter=String
Text=2022 INTRODB S18 TH 1100 - 1200
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=482
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter21]
Meter=String
Text=2048 LASARE1 A51 F  0730 - 1630
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=496
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter22]
Meter=String
Text=170  SCIMATC S17 T  1245 - 1345
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=510
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter23]
Meter=String
Text=1809 SOCTEC2 S11 MW 1615 - 1745
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=524
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

[Meter24]
Meter=String
Text=www.dlsu.edu.ph/offices/registrar/schedules/enroll_ug.pdf
X=(#alignRight# = 1 ? #SCREENAREAWIDTH# : 0)
Y=538
FontFace=Segoe UI
FontSize=8
FontColor=242,206,218
StringAlign=Right
AntiAlias=1
DynamicVariables=1

1