[Variables]
meterID=8/20
Game0Banner=388080
Game1Banner=368340
Game2Banner=570
Game3Banner=322750
Game4Banner=70400
Game5Banner=211820
Game6Banner=413150
Game7Banner=253250

[Game0]
Meter=Image
ImageName=DownloadFile/#Game0Banner#.jpg
H=122.5
X=20
Y=20
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game0Banner#"]
MouseOverAction=[!SetOption Game0 Greyscale 0][!UpdateMeter Game0][!Redraw]
MouseLeaveAction=[!SetOption Game0 Greyscale 1][!UpdateMeter Game0][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game1]
Meter=Image
ImageName=DownloadFile/#Game1Banner#.jpg
H=122.5
X=20
Y=162.5
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game1Banner#"]
MouseOverAction=[!SetOption Game1 Greyscale 0][!UpdateMeter Game1][!Redraw]
MouseLeaveAction=[!SetOption Game1 Greyscale 1][!UpdateMeter Game1][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game2]
Meter=Image
ImageName=DownloadFile/#Game2Banner#.jpg
H=122.5
X=20
Y=305
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game2Banner#"]
MouseOverAction=[!SetOption Game2 Greyscale 0][!UpdateMeter Game2][!Redraw]
MouseLeaveAction=[!SetOption Game2 Greyscale 1][!UpdateMeter Game2][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game3]
Meter=Image
ImageName=DownloadFile/#Game3Banner#.jpg
H=122.5
X=20
Y=447.5
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game3Banner#"]
MouseOverAction=[!SetOption Game3 Greyscale 0][!UpdateMeter Game3][!Redraw]
MouseLeaveAction=[!SetOption Game3 Greyscale 1][!UpdateMeter Game3][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game4]
Meter=Image
ImageName=DownloadFile/#Game4Banner#.jpg
H=122.5
X=20
Y=590
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game4Banner#"]
MouseOverAction=[!SetOption Game4 Greyscale 0][!UpdateMeter Game4][!Redraw]
MouseLeaveAction=[!SetOption Game4 Greyscale 1][!UpdateMeter Game4][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game5]
Meter=Image
ImageName=DownloadFile/#Game5Banner#.jpg
H=122.5
X=20
Y=732.5
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game5Banner#"]
MouseOverAction=[!SetOption Game5 Greyscale 0][!UpdateMeter Game5][!Redraw]
MouseLeaveAction=[!SetOption Game5 Greyscale 1][!UpdateMeter Game5][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game6]
Meter=Image
ImageName=DownloadFile/#Game6Banner#.jpg
H=122.5
X=20
Y=875
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game6Banner#"]
MouseOverAction=[!SetOption Game6 Greyscale 0][!UpdateMeter Game6][!Redraw]
MouseLeaveAction=[!SetOption Game6 Greyscale 1][!UpdateMeter Game6][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game7]
Meter=Image
ImageName=DownloadFile/#Game7Banner#.jpg
H=122.5
X=20
Y=1017.5
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game7Banner#"]
MouseOverAction=[!SetOption Game7 Greyscale 0][!UpdateMeter Game7][!Redraw]
MouseLeaveAction=[!SetOption Game7 Greyscale 1][!UpdateMeter Game7][!Redraw]
DynamicVariables=1
Group=SteamGames

