#1505287095/107855939620dragonnest586140djmaxtrilogy580200362890538680wotlk58347042966052422057021182036567036834041315038808032275043196070400253250264710

[Variables]
Game0Banner=362890
Game1Banner=586140
Game2Banner=365670
Game3Banner=388080
Game4Banner=368340
Game5Banner=djmaxtrilogy

[Game0]
Meter=Image
ImageName=DownloadFile/#Game0Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*0 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(0)]
RightMouseUpAction=[!CommandMeasure Script rmb(0)]
DynamicVariables=1
Group=GameLibrary

[Game1]
Meter=Image
ImageName=DownloadFile/#Game1Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*1 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(1)]
RightMouseUpAction=[!CommandMeasure Script rmb(1)]
DynamicVariables=1
Group=GameLibrary

[Game2]
Meter=Image
ImageName=DownloadFile/#Game2Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*2 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(2)]
RightMouseUpAction=[!CommandMeasure Script rmb(2)]
DynamicVariables=1
Group=GameLibrary

[Game3]
Meter=Image
ImageName=DownloadFile/#Game3Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*3 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(3)]
RightMouseUpAction=[!CommandMeasure Script rmb(3)]
DynamicVariables=1
Group=GameLibrary

[Game4]
Meter=Image
ImageName=DownloadFile/#Game4Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*4 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(4)]
RightMouseUpAction=[!CommandMeasure Script rmb(4)]
DynamicVariables=1
Group=GameLibrary

[Game5]
Meter=Image
ImageName=DownloadFile/#Game5Banner#.jpg
MaskImageName=mask
H=(#meterH# - #spacing#)
X=#spacing#
Y=(#meterH#*5 + #spacing#*2 + 40)
LeftMouseUpAction=[!CommandMeasure Script lmb(5)]
RightMouseUpAction=[!CommandMeasure Script rmb(5)]
DynamicVariables=1
Group=GameLibrary

