[Variables]
meterID=8/20/Blender 2.78/Borderless Gaming/CrossCode/Dota 2/Drifting Lands/Recettear: An Item Shop's Tale/Starbound/Stardew Valley/Stonehearth/Subnautica/Wallpaper Engine
Game0Banner=365670
Game1Banner=388080
Game2Banner=368340
Game3Banner=570
Game4Banner=322750
Game5Banner=70400
Game6Banner=211820
Game7Banner=413150

[Game0]
Meter=Image
ImageName=DownloadFile/#Game0Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*0+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game0Banner#"]
MouseOverAction=[!SetOption Game0 Greyscale 0][!UpdateMeter Game0][!Redraw]
MouseLeaveAction=[!SetOption Game0 Greyscale 1][!UpdateMeter Game0][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game1]
Meter=Image
ImageName=DownloadFile/#Game1Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*1+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game1Banner#"]
MouseOverAction=[!SetOption Game1 Greyscale 0][!UpdateMeter Game1][!Redraw]
MouseLeaveAction=[!SetOption Game1 Greyscale 1][!UpdateMeter Game1][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game2]
Meter=Image
ImageName=DownloadFile/#Game2Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*2+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game2Banner#"]
MouseOverAction=[!SetOption Game2 Greyscale 0][!UpdateMeter Game2][!Redraw]
MouseLeaveAction=[!SetOption Game2 Greyscale 1][!UpdateMeter Game2][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game3]
Meter=Image
ImageName=DownloadFile/#Game3Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*3+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game3Banner#"]
MouseOverAction=[!SetOption Game3 Greyscale 0][!UpdateMeter Game3][!Redraw]
MouseLeaveAction=[!SetOption Game3 Greyscale 1][!UpdateMeter Game3][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game4]
Meter=Image
ImageName=DownloadFile/#Game4Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*4+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game4Banner#"]
MouseOverAction=[!SetOption Game4 Greyscale 0][!UpdateMeter Game4][!Redraw]
MouseLeaveAction=[!SetOption Game4 Greyscale 1][!UpdateMeter Game4][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game5]
Meter=Image
ImageName=DownloadFile/#Game5Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*5+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game5Banner#"]
MouseOverAction=[!SetOption Game5 Greyscale 0][!UpdateMeter Game5][!Redraw]
MouseLeaveAction=[!SetOption Game5 Greyscale 1][!UpdateMeter Game5][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game6]
Meter=Image
ImageName=DownloadFile/#Game6Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*6+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game6Banner#"]
MouseOverAction=[!SetOption Game6 Greyscale 0][!UpdateMeter Game6][!Redraw]
MouseLeaveAction=[!SetOption Game6 Greyscale 1][!UpdateMeter Game6][!Redraw]
DynamicVariables=1
Group=SteamGames

[Game7]
Meter=Image
ImageName=DownloadFile/#Game7Banner#.jpg
H=((#SCREENAREAHEIGHT#-40)/8-22.5)
X=20
Y=(((#SCREENAREAHEIGHT#-40)/8-2.5)*7+20)
Greyscale=1
LeftMouseUpAction=["steam://rungameid/#Game7Banner#"]
MouseOverAction=[!SetOption Game7 Greyscale 0][!UpdateMeter Game7][!Redraw]
MouseLeaveAction=[!SetOption Game7 Greyscale 1][!UpdateMeter Game7][!Redraw]
DynamicVariables=1
Group=SteamGames

