[dota2]
Meter=Image
ImageName=dota2
W=30
H=30
Hidden=1

[dota2Process]
Measure=Plugin
Plugin=Process
ProcessName=dota2.exe

[PaintDotNet]
Meter=Image
ImageName=PaintDotNet
W=30
H=30
Hidden=1

[PaintDotNetProcess]
Measure=Plugin
Plugin=Process
ProcessName=PaintDotNet.exe

[explorer]
Meter=Image
ImageName=explorer
W=30
H=30
Hidden=1

[explorerProcess]
Measure=Plugin
Plugin=Process
ProcessName=explorer.exe

[uTorrent]
Meter=Image
ImageName=uTorrent
W=30
H=30
Hidden=1

[uTorrentProcess]
Measure=Plugin
Plugin=Process
ProcessName=uTorrent.exe

