#48160040

[B0]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=0

[B1]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=1

[B2]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=2

[B3]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=3

[B4]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=4

[B5]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=5

[B6]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=6

[B7]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=7

[B8]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=8

[B9]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=9

[B10]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=10

[B11]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=11

[B12]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=12

[B13]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=13

[B14]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=14

[B15]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=15

[B16]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=16

[B17]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=17

[B18]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=18

[B19]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=19

[B20]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=20

[B21]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=21

[B22]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=22

[B23]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=23

[B24]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=24

[B25]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=25

[B26]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=26

[B27]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=27

[B28]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=28

[B29]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=29

[B30]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=30

[B31]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=31

[B32]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=32

[B33]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=33

[B34]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=34

[B35]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=35

[B36]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=36

[B37]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=37

[B38]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=38

[B39]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=39

[B40]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=40

[B41]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=41

[B42]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=42

[B43]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=43

[B44]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=44

[B45]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=45

[B46]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=46

[B47]
Measure=Plugin
Group=Bands
Plugin=AudioLevel
Parent=Audio
Type=Band
BandIdx=47

[Variables]
M0=(1/(#Bands# - 1)*#Width#),((1 - [B1])*#Height#),(0.5/(#Bands# - 1)*#Width#),((1 - [B1])*#Height#),(0.5/(#Bands# - 1)*#Width#),((1 - ([B1]*2 - [B2]))*#Height#)
M1=(2/(#Bands# - 1)*#Width#),((1 - [B2])*#Height#),(1.5/(#Bands# - 1)*#Width#),((1 - [B2])*#Height#),(1.5/(#Bands# - 1)*#Width#),((1 - ([B2]*2 - [B3]))*#Height#)
M2=(3/(#Bands# - 1)*#Width#),((1 - [B3])*#Height#),(2.5/(#Bands# - 1)*#Width#),((1 - [B3])*#Height#),(2.5/(#Bands# - 1)*#Width#),((1 - ([B3]*2 - [B4]))*#Height#)
M3=(4/(#Bands# - 1)*#Width#),((1 - [B4])*#Height#),(3.5/(#Bands# - 1)*#Width#),((1 - [B4])*#Height#),(3.5/(#Bands# - 1)*#Width#),((1 - ([B4]*2 - [B5]))*#Height#)
M4=(5/(#Bands# - 1)*#Width#),((1 - [B5])*#Height#),(4.5/(#Bands# - 1)*#Width#),((1 - [B5])*#Height#),(4.5/(#Bands# - 1)*#Width#),((1 - ([B5]*2 - [B6]))*#Height#)
M5=(6/(#Bands# - 1)*#Width#),((1 - [B6])*#Height#),(5.5/(#Bands# - 1)*#Width#),((1 - [B6])*#Height#),(5.5/(#Bands# - 1)*#Width#),((1 - ([B6]*2 - [B7]))*#Height#)
M6=(7/(#Bands# - 1)*#Width#),((1 - [B7])*#Height#),(6.5/(#Bands# - 1)*#Width#),((1 - [B7])*#Height#),(6.5/(#Bands# - 1)*#Width#),((1 - ([B7]*2 - [B8]))*#Height#)
M7=(8/(#Bands# - 1)*#Width#),((1 - [B8])*#Height#),(7.5/(#Bands# - 1)*#Width#),((1 - [B8])*#Height#),(7.5/(#Bands# - 1)*#Width#),((1 - ([B8]*2 - [B9]))*#Height#)
M8=(9/(#Bands# - 1)*#Width#),((1 - [B9])*#Height#),(8.5/(#Bands# - 1)*#Width#),((1 - [B9])*#Height#),(8.5/(#Bands# - 1)*#Width#),((1 - ([B9]*2 - [B10]))*#Height#)
M9=(10/(#Bands# - 1)*#Width#),((1 - [B10])*#Height#),(9.5/(#Bands# - 1)*#Width#),((1 - [B10])*#Height#),(9.5/(#Bands# - 1)*#Width#),((1 - ([B10]*2 - [B11]))*#Height#)
M10=(11/(#Bands# - 1)*#Width#),((1 - [B11])*#Height#),(10.5/(#Bands# - 1)*#Width#),((1 - [B11])*#Height#),(10.5/(#Bands# - 1)*#Width#),((1 - ([B11]*2 - [B12]))*#Height#)
M11=(12/(#Bands# - 1)*#Width#),((1 - [B12])*#Height#),(11.5/(#Bands# - 1)*#Width#),((1 - [B12])*#Height#),(11.5/(#Bands# - 1)*#Width#),((1 - ([B12]*2 - [B13]))*#Height#)
M12=(13/(#Bands# - 1)*#Width#),((1 - [B13])*#Height#),(12.5/(#Bands# - 1)*#Width#),((1 - [B13])*#Height#),(12.5/(#Bands# - 1)*#Width#),((1 - ([B13]*2 - [B14]))*#Height#)
M13=(14/(#Bands# - 1)*#Width#),((1 - [B14])*#Height#),(13.5/(#Bands# - 1)*#Width#),((1 - [B14])*#Height#),(13.5/(#Bands# - 1)*#Width#),((1 - ([B14]*2 - [B15]))*#Height#)
M14=(15/(#Bands# - 1)*#Width#),((1 - [B15])*#Height#),(14.5/(#Bands# - 1)*#Width#),((1 - [B15])*#Height#),(14.5/(#Bands# - 1)*#Width#),((1 - ([B15]*2 - [B16]))*#Height#)
M15=(16/(#Bands# - 1)*#Width#),((1 - [B16])*#Height#),(15.5/(#Bands# - 1)*#Width#),((1 - [B16])*#Height#),(15.5/(#Bands# - 1)*#Width#),((1 - ([B16]*2 - [B17]))*#Height#)
M16=(17/(#Bands# - 1)*#Width#),((1 - [B17])*#Height#),(16.5/(#Bands# - 1)*#Width#),((1 - [B17])*#Height#),(16.5/(#Bands# - 1)*#Width#),((1 - ([B17]*2 - [B18]))*#Height#)
M17=(18/(#Bands# - 1)*#Width#),((1 - [B18])*#Height#),(17.5/(#Bands# - 1)*#Width#),((1 - [B18])*#Height#),(17.5/(#Bands# - 1)*#Width#),((1 - ([B18]*2 - [B19]))*#Height#)
M18=(19/(#Bands# - 1)*#Width#),((1 - [B19])*#Height#),(18.5/(#Bands# - 1)*#Width#),((1 - [B19])*#Height#),(18.5/(#Bands# - 1)*#Width#),((1 - ([B19]*2 - [B20]))*#Height#)
M19=(20/(#Bands# - 1)*#Width#),((1 - [B20])*#Height#),(19.5/(#Bands# - 1)*#Width#),((1 - [B20])*#Height#),(19.5/(#Bands# - 1)*#Width#),((1 - ([B20]*2 - [B21]))*#Height#)
M20=(21/(#Bands# - 1)*#Width#),((1 - [B21])*#Height#),(20.5/(#Bands# - 1)*#Width#),((1 - [B21])*#Height#),(20.5/(#Bands# - 1)*#Width#),((1 - ([B21]*2 - [B22]))*#Height#)
M21=(22/(#Bands# - 1)*#Width#),((1 - [B22])*#Height#),(21.5/(#Bands# - 1)*#Width#),((1 - [B22])*#Height#),(21.5/(#Bands# - 1)*#Width#),((1 - ([B22]*2 - [B23]))*#Height#)
M22=(23/(#Bands# - 1)*#Width#),((1 - [B23])*#Height#),(22.5/(#Bands# - 1)*#Width#),((1 - [B23])*#Height#),(22.5/(#Bands# - 1)*#Width#),((1 - ([B23]*2 - [B24]))*#Height#)
M23=(24/(#Bands# - 1)*#Width#),((1 - [B24])*#Height#),(23.5/(#Bands# - 1)*#Width#),((1 - [B24])*#Height#),(23.5/(#Bands# - 1)*#Width#),((1 - ([B24]*2 - [B25]))*#Height#)
M24=(25/(#Bands# - 1)*#Width#),((1 - [B25])*#Height#),(24.5/(#Bands# - 1)*#Width#),((1 - [B25])*#Height#),(24.5/(#Bands# - 1)*#Width#),((1 - ([B25]*2 - [B26]))*#Height#)
M25=(26/(#Bands# - 1)*#Width#),((1 - [B26])*#Height#),(25.5/(#Bands# - 1)*#Width#),((1 - [B26])*#Height#),(25.5/(#Bands# - 1)*#Width#),((1 - ([B26]*2 - [B27]))*#Height#)
M26=(27/(#Bands# - 1)*#Width#),((1 - [B27])*#Height#),(26.5/(#Bands# - 1)*#Width#),((1 - [B27])*#Height#),(26.5/(#Bands# - 1)*#Width#),((1 - ([B27]*2 - [B28]))*#Height#)
M27=(28/(#Bands# - 1)*#Width#),((1 - [B28])*#Height#),(27.5/(#Bands# - 1)*#Width#),((1 - [B28])*#Height#),(27.5/(#Bands# - 1)*#Width#),((1 - ([B28]*2 - [B29]))*#Height#)
M28=(29/(#Bands# - 1)*#Width#),((1 - [B29])*#Height#),(28.5/(#Bands# - 1)*#Width#),((1 - [B29])*#Height#),(28.5/(#Bands# - 1)*#Width#),((1 - ([B29]*2 - [B30]))*#Height#)
M29=(30/(#Bands# - 1)*#Width#),((1 - [B30])*#Height#),(29.5/(#Bands# - 1)*#Width#),((1 - [B30])*#Height#),(29.5/(#Bands# - 1)*#Width#),((1 - ([B30]*2 - [B31]))*#Height#)
M30=(31/(#Bands# - 1)*#Width#),((1 - [B31])*#Height#),(30.5/(#Bands# - 1)*#Width#),((1 - [B31])*#Height#),(30.5/(#Bands# - 1)*#Width#),((1 - ([B31]*2 - [B32]))*#Height#)
M31=(32/(#Bands# - 1)*#Width#),((1 - [B32])*#Height#),(31.5/(#Bands# - 1)*#Width#),((1 - [B32])*#Height#),(31.5/(#Bands# - 1)*#Width#),((1 - ([B32]*2 - [B33]))*#Height#)
M32=(33/(#Bands# - 1)*#Width#),((1 - [B33])*#Height#),(32.5/(#Bands# - 1)*#Width#),((1 - [B33])*#Height#),(32.5/(#Bands# - 1)*#Width#),((1 - ([B33]*2 - [B34]))*#Height#)
M33=(34/(#Bands# - 1)*#Width#),((1 - [B34])*#Height#),(33.5/(#Bands# - 1)*#Width#),((1 - [B34])*#Height#),(33.5/(#Bands# - 1)*#Width#),((1 - ([B34]*2 - [B35]))*#Height#)
M34=(35/(#Bands# - 1)*#Width#),((1 - [B35])*#Height#),(34.5/(#Bands# - 1)*#Width#),((1 - [B35])*#Height#),(34.5/(#Bands# - 1)*#Width#),((1 - ([B35]*2 - [B36]))*#Height#)
M35=(36/(#Bands# - 1)*#Width#),((1 - [B36])*#Height#),(35.5/(#Bands# - 1)*#Width#),((1 - [B36])*#Height#),(35.5/(#Bands# - 1)*#Width#),((1 - ([B36]*2 - [B37]))*#Height#)
M36=(37/(#Bands# - 1)*#Width#),((1 - [B37])*#Height#),(36.5/(#Bands# - 1)*#Width#),((1 - [B37])*#Height#),(36.5/(#Bands# - 1)*#Width#),((1 - ([B37]*2 - [B38]))*#Height#)
M37=(38/(#Bands# - 1)*#Width#),((1 - [B38])*#Height#),(37.5/(#Bands# - 1)*#Width#),((1 - [B38])*#Height#),(37.5/(#Bands# - 1)*#Width#),((1 - ([B38]*2 - [B39]))*#Height#)
M38=(39/(#Bands# - 1)*#Width#),((1 - [B39])*#Height#),(38.5/(#Bands# - 1)*#Width#),((1 - [B39])*#Height#),(38.5/(#Bands# - 1)*#Width#),((1 - ([B39]*2 - [B40]))*#Height#)
M39=(40/(#Bands# - 1)*#Width#),((1 - [B40])*#Height#),(39.5/(#Bands# - 1)*#Width#),((1 - [B40])*#Height#),(39.5/(#Bands# - 1)*#Width#),((1 - ([B40]*2 - [B41]))*#Height#)
M40=(41/(#Bands# - 1)*#Width#),((1 - [B41])*#Height#),(40.5/(#Bands# - 1)*#Width#),((1 - [B41])*#Height#),(40.5/(#Bands# - 1)*#Width#),((1 - ([B41]*2 - [B42]))*#Height#)
M41=(42/(#Bands# - 1)*#Width#),((1 - [B42])*#Height#),(41.5/(#Bands# - 1)*#Width#),((1 - [B42])*#Height#),(41.5/(#Bands# - 1)*#Width#),((1 - ([B42]*2 - [B43]))*#Height#)
M42=(43/(#Bands# - 1)*#Width#),((1 - [B43])*#Height#),(42.5/(#Bands# - 1)*#Width#),((1 - [B43])*#Height#),(42.5/(#Bands# - 1)*#Width#),((1 - ([B43]*2 - [B44]))*#Height#)
M43=(44/(#Bands# - 1)*#Width#),((1 - [B44])*#Height#),(43.5/(#Bands# - 1)*#Width#),((1 - [B44])*#Height#),(43.5/(#Bands# - 1)*#Width#),((1 - ([B44]*2 - [B45]))*#Height#)
M44=(45/(#Bands# - 1)*#Width#),((1 - [B45])*#Height#),(44.5/(#Bands# - 1)*#Width#),((1 - [B45])*#Height#),(44.5/(#Bands# - 1)*#Width#),((1 - ([B45]*2 - [B46]))*#Height#)
M45=(46/(#Bands# - 1)*#Width#),((1 - [B46])*#Height#),(45.5/(#Bands# - 1)*#Width#),((1 - [B46])*#Height#),(45.5/(#Bands# - 1)*#Width#),((1 - ([B46]*2 - [B47]))*#Height#)
M46=(47/(#Bands# - 1)*#Width#),((1 - [B47])*#Height#),(46.5/(#Bands# - 1)*#Width#),((1 - [B47])*#Height#),(46.5/(#Bands# - 1)*#Width#),((1 - ([B47]*2 - [B47]))*#Height#)

[Visualizer]
Meter=Shape
Group=Visualizer
UpdateDivider=1
DynamicVariables=1
Shape=Path MyPath | StrokeWidth 0 | Fill Color #Color#,(#OpacityAsBass# = 1 ? Max([B1],[B4])*(#Opacity# - #OpacityAsBass_IdleOpacity#) + #OpacityAsBass_IdleOpacity# : #Opacity#)
MyPath=0,#Height# | LineTo 0,((1 - [B0])*#Height#) | CurveTo #M0# | CurveTo #M1# | CurveTo #M2# | CurveTo #M3# | CurveTo #M4# | CurveTo #M5# | CurveTo #M6# | CurveTo #M7# | CurveTo #M8# | CurveTo #M9# | CurveTo #M10# | CurveTo #M11# | CurveTo #M12# | CurveTo #M13# | CurveTo #M14# | CurveTo #M15# | CurveTo #M16# | CurveTo #M17# | CurveTo #M18# | CurveTo #M19# | CurveTo #M20# | CurveTo #M21# | CurveTo #M22# | CurveTo #M23# | CurveTo #M24# | CurveTo #M25# | CurveTo #M26# | CurveTo #M27# | CurveTo #M28# | CurveTo #M29# | CurveTo #M30# | CurveTo #M31# | CurveTo #M32# | CurveTo #M33# | CurveTo #M34# | CurveTo #M35# | CurveTo #M36# | CurveTo #M37# | CurveTo #M38# | CurveTo #M39# | CurveTo #M40# | CurveTo #M41# | CurveTo #M42# | CurveTo #M43# | CurveTo #M44# | CurveTo #M45# | CurveTo #M46# | LineTo #Width#,#Height#
